"""Shared constants for DoomArena tools."""

EMPTY_PLACEHOLDER = "[EMPTY]"
MISSING_INPUT_PLACEHOLDER = "[missing input_text]"
MISSING_OUTPUT_PLACEHOLDER = "[missing output_text]"

PLACEHOLDER_INPUT_VALUES = {EMPTY_PLACEHOLDER, MISSING_INPUT_PLACEHOLDER}
PLACEHOLDER_OUTPUT_VALUES = {EMPTY_PLACEHOLDER, MISSING_OUTPUT_PLACEHOLDER}
