name: run-demo

on:
  workflow_dispatch:
    inputs:
      trials:
        description: "Trials per seed"
        required: false
        default: "3"
      seeds:
        description: "Seeds (comma-separated)"
        required: false
        default: "11,12"
      mode:
        description: "Mode (SHIM or REAL)"
        required: false
        default: "SHIM"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set RUN_ID (once)
        id: set-run-id
        shell: bash
        run: |
          RUN_ID="$(date -u +%Y%m%d-%H%M%S)"
          echo "RUN_ID=$RUN_ID" >> "$GITHUB_ENV"
          echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"
          echo "RUN_ID=$RUN_ID"

      - name: Install
        shell: bash
        run: make install

      - name: Run demo (single RUN_ID with both experiments)
        env:
          TRIALS: ${{ inputs.trials }}
          SEEDS: ${{ inputs.seeds }}
          MODE: ${{ inputs.mode }}
          RUN_ID: ${{ env.RUN_ID }}
        shell: bash
        run: |
          make demo TRIALS="${TRIALS}" SEEDS="${SEEDS}" MODE="${MODE}" RUN_ID="${RUN_ID}"

      - name: Report run outputs
        env:
          RUN_ID: ${{ env.RUN_ID }}
        shell: bash
        run: |
          make report RUN_ID="${RUN_ID}"

      - name: Threshold summary
        if: always()
        shell: bash
        continue-on-error: true
        env:
          RUN_ID: ${{ env.RUN_ID }}
          STRICT: '0'
        run: |
          set -euo pipefail
          make check-thresholds STRICT="${STRICT}"

      - name: Refresh latest pointer
        shell: bash
        run: |
          make latest

      - name: On latest failure, print context
        if: failure()
        shell: bash
        run: |
          echo "ERR: latest pointer failed; check tools/latest_run.py and artifacts from previous steps."

      - name: Tidy run directory (remove duplicates)
        if: ${{ always() }}
        env:
          RUN_ID: ${{ env.RUN_ID }}
        shell: bash
        run: |
          make tidy-run RUN_ID="${RUN_ID}"

      - name: Upload full RUN_DIR
        if: ${{ always() && steps.set-run-id.outputs.run_id != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ env.RUN_ID }}
          path: results/${{ env.RUN_ID }}/
          if-no-files-found: error
          retention-days: 7

      - name: Upload latest artifacts (from results/)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: latest-artifacts
          path: |
            results/summary.csv
            results/summary.svg
            results/index.html
            results/run.json
          if-no-files-found: warn
          retention-days: 7
