name: run-demo

on:
  workflow_dispatch:
    inputs:
      trials:
        description: "Trials per seed"
        required: false
        default: "3"
      seeds:
        description: "Seeds (comma-separated)"
        required: false
        default: "11,12"
      mode:
        description: "Mode (SHIM or REAL)"
        required: false
        default: "SHIM"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set RUN_ID (once)
        id: set-run-id
        run: |
          RUN_ID="$(date -u +%Y%m%d-%H%M%S)"
          echo "RUN_ID=$RUN_ID" >> "$GITHUB_ENV"
          echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"
          echo "RUN_ID=$RUN_ID"

      - name: Install
        run: make install

      - name: Run demo (single RUN_ID with both experiments)
        env:
          TRIALS: ${{ inputs.trials }}
          SEEDS: ${{ inputs.seeds }}
          MODE: ${{ inputs.mode }}
          RUN_ID: ${{ steps.set-run-id.outputs.run_id }}
        run: |
          make demo TRIALS="${TRIALS}" SEEDS="${SEEDS}" MODE="${MODE}" RUN_ID="${RUN_ID}"

      - name: Report + publish LATEST
        env:
          RUN_ID: ${{ steps.set-run-id.outputs.run_id }}
        run: |
          make report RUN_ID="${RUN_ID}"
          make latest

      - name: Add timestamped copies inside run dir
        env:
          RUN_ID: ${{ steps.set-run-id.outputs.run_id }}
        run: |
          d="results/${RUN_ID}"
          test -d "$d" || { echo "Missing $d"; exit 1; }
          for f in summary.csv summary.svg summary.md index.html run.json; do
            if [ -f "$d/$f" ]; then
              cp -f "$d/$f" "$d/${f%.*}_${RUN_ID}.${f##*.}"
            fi
          done

      - name: Upload full RUN_DIR
        if: ${{ steps.set-run-id.outputs.run_id != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ steps.set-run-id.outputs.run_id }}
          path: results/${{ steps.set-run-id.outputs.run_id }}/
          if-no-files-found: error
          retention-days: 7

      - name: Upload latest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latest-artifacts
          path: |
            results/LATEST/summary.csv
            results/LATEST/summary.svg
            results/LATEST/index.html
            results/LATEST/run.json
          if-no-files-found: error
          retention-days: 7
