name: run-real-escalating
on:
  workflow_dispatch:
    inputs:
      trials:
        description: "Trials per seed"
        default: "3"
        type: string
      seeds:
        description: "Comma-separated seeds"
        default: "11,12"
        type: string
      model:
        description: "Groq model"
        type: choice
        default: llama-3.1-8b-instant
        options:
          - llama-3.1-8b-instant
          - llama-3.3-70b-versatile
jobs:
  real:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install light deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python - <<'PY'
          # stdlib-only runners; external deps handled in make
          PY
      - name: Run REAL escalating experiment
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TRIALS: ${{ inputs.trials }}
          SEEDS: ${{ inputs.seeds }}
          REAL_MODEL: ${{ inputs.model }}
        run: |
          . .venv/bin/activate
          RUN_ID="real_${{ github.run_id }}_${{ github.run_attempt }}_$(date -u +%Y%m%d-%H%M%S)"
          export RUN_ID
          export RUN_DIR="results/${RUN_ID}"
          make real-escalating RUN_ID="${RUN_ID}"
      - name: Determine RUN_ID
        id: rid
        run: |
          RID="$(cat results/.run_id 2>/dev/null || true)"
          echo "run_id=$RID" >> "$GITHUB_OUTPUT"
          echo "RUN_ID=$RID"
      - name: Upload run artifacts
        if: steps.rid.outputs.run_id != ''
        uses: actions/upload-artifact@v4
        with:
          name: real-escalating-${{ steps.rid.outputs.run_id }}
          path: results/${{ steps.rid.outputs.run_id }}/
          if-no-files-found: error
          retention-days: 7
      - name: Upload latest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latest-artifacts
          path: |
            results/LATEST/summary.csv
            results/LATEST/summary.svg
            results/LATEST/summary.md
            results/LATEST/index.html
            results/LATEST/run.json
          if-no-files-found: ignore
          retention-days: 7
