name: run-demo
on:
  workflow_dispatch:
    inputs:
      trials:
        description: "Trials per seed"
        required: false
        default: "3"
      seeds:
        description: "Seeds (comma-separated)"
        required: false
        default: "11,12"
      mode:
        description: "Mode (SHIM or REAL)"
        required: false
        default: "SHIM"
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: make install
      - name: Run demo (single RUN_ID with both experiments)
        env:
          TRIALS: ${{ inputs.trials }}
          SEEDS: ${{ inputs.seeds }}
          MODE: ${{ inputs.mode }}
        run: |
          make demo TRIALS="${TRIALS}" SEEDS="${SEEDS}" MODE="${MODE}"
      - name: Report + publish LATEST
        run: |
          make report
          make latest
      - name: Upload latest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latest-artifacts
          path: |
            results/LATEST/summary.csv
            results/LATEST/summary.svg
            results/LATEST/index.html
            results/LATEST/run.json
          if-no-files-found: error
          retention-days: 7
