name: smoke
on:
  pull_request:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install doomarena doomarena-taubench pytest pyyaml pandas matplotlib

      - name: Run tiny SHIM demo
        run: |
          make demo

      - name: Report + refresh LATEST
        run: |
          make report
          make latest

      - name: Upload latest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latest-artifacts
          path: results/LATEST/*
          if-no-files-found: error
          retention-days: 7

      - name: Compose PR comment
        id: compose
        run: |
          python tools/pr_comment_latest.py > pr_body.md
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat pr_body.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const body = core.getInput('body', { required: true });
            const { context, github } = require('@actions/github');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
        env:
          body: ${{ steps.compose.outputs.body }}
