name: smoke

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # Headless plotting for matplotlib
      MPLBACKEND: Agg
      # Makefile overrides we want for a quick SHIM sweep
      EXP: airline_escalating_v1
      MODE: SHIM
      SEEDS: "41,42,43"
      TRIALS: "5"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create venv and install deps
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip wheel
          pip install -r requirements-ci.txt

      - name: Smoke: sweep + report (SHIM)
        shell: bash
        run: |
          source .venv/bin/activate
          make sweep EXP="$EXP" MODE="$MODE" SEEDS="$SEEDS" TRIALS="$TRIALS"
          echo "---- results/summary.csv (head) ----"
          head -5 results/summary.csv || true
          echo "---- grep ASR from run logs if present ----"
          grep -R --line-number -E 'ASR=' || true

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: results-csv
          path: results/summary.csv
          if-no-files-found: ignore

      - name: Upload plot
        uses: actions/upload-artifact@v4
        with:
          name: results-plot
          path: results/summary.png
          if-no-files-found: ignore
