name: smoke

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  shim:
    name: SHIM sweep
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # NOTE: no pip cache here (avoids “no requirements/pyproject found” error)

      - name: Bootstrap & run SHIM sweep via Makefile
        env:
          EXP: airline_escalating_v1
          TRIALS: "5"
          SEEDS: "41,42,43"
          MODE: SHIM
        run: |
          make install
          make xsweep EXP="$EXP" TRIALS="$TRIALS" SEEDS="$SEEDS" MODE="$MODE"
          make report

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            results/**
            results/summary.csv
            results/summary.png
          if-no-files-found: ignore
