name: smoke

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shim:
    name: SHIM sweep
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install -U pip wheel
          pip install -U doomarena doomarena-taubench pytest pyyaml matplotlib

      - name: Run SHIM sweep
        env:
          EXP: airline_escalating_v1
          TRIALS: '5'
          SEEDS: '41,42,43'
          MODE: SHIM
        run: |
          . .venv/bin/activate
          make xsweep EXP="$EXP" TRIALS="$TRIALS" SEEDS="$SEEDS" MODE="$MODE"
          make report

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            results/**
            results/summary.csv
            results/summary.png
          if-no-files-found: warn
