name: smoke

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
      pull-requests: write
    env:
      # Headless plotting for matplotlib
      MPLBACKEND: Agg
      # Makefile overrides we want for a quick SHIM sweep
      EXP: airline_escalating_v1
      MODE: SHIM
      SEEDS: '41,42,43'
      TRIALS: '5'
    steps:
      - name: Add approval-friendly label
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const label = 'ci: smoke';
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;

            async function ensureLabelExists() {
              try {
                await github.rest.issues.getLabel({ owner, repo, name: label });
              } catch (error) {
                if (error.status === 404) {
                  await github.rest.issues.createLabel({
                    owner,
                    repo,
                    name: label,
                    color: '0E8A16',
                    description: 'Indicates that the smoke workflow ran for approval readiness.',
                  });
                } else {
                  throw error;
                }
              }
            }

            await ensureLabelExists();
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: [label],
            });

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Bootstrap & run SHIM sweep via Makefile
        env:
          EXP: airline_escalating_v1
          TRIALS: '5'
          SEEDS: '41,42,43'
          MODE: SHIM
        run: |
          make install
          make xsweep EXP="$EXP" TRIALS="$TRIALS" SEEDS="$SEEDS" MODE="$MODE"
          make report

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            results/**
            results/summary.csv
            results/summary.png
          if-no-files-found: warn
