name: smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      MPLBACKEND: Agg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: System deps for headless matplotlib
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev

      - name: Install project deps (creates .venv)
        run: make install

      - name: Fast SHIM sweep across all configs
        run: |
          make xsweep-all MODE=SHIM TRIALS=2 SEEDS="41,42" CONFIG_GLOB="configs/*/run.yaml"

      - name: Aggregate + report
        run: make report

      - name: Show summary head
        run: |
          head -5 results/summary.csv || true

      - name: Upload smoke artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts-${{ github.run_number }}
          if-no-files-found: warn
          path: |
            results/summary.csv
            results/summary.png
            README.md
